{
 "title": "Chia",
 "description": "Chia Network",
 "tags": [
  "system",
  "prometheus",
  "online",
  "home"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": { "query": "label_values($tag)" } },
   { "name": "tag", "query": "instance, alias" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_farm_summary_status", "legendFormat": " " }
   ]
  },
  {
   "title": "Farm Disk Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"//192.168.4.171/Public\", mountpoint=\"/mnt/farmer1\"}",
     "legendFormat": "farmer1"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"//192.168.4.171/Public_2\", mountpoint=\"/mnt/farmer2\"}",
     "legendFormat": "farmer2"
    }
   ]
  },
  {
   "title": "Network Stake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "chia_farm_summary_total_plot_size * 100/chia_farm_summary_estimated_network_space"
    }
   ]
  },
  {
   "title": "Time To Win",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farm_summary_expected_time_to_win",
     "legendFormat": "ETW"
    }
   ]
  },
  {
   "title": "XCH",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farm_summary_total_chia_farmed",
     "legendFormat": "XCH"
    }
   ]
  },
  {
   "title": "XCH-USD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "coin_market_quote_USD" }
   ]
  },
  {
   "title": "Plots In Progress",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farm_summary_plots_in_progress",
     "legendFormat": "Plots In Progress"
    }
   ]
  },
  {
   "title": "Completed Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_farm_summary_total_plot_size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{$tag=\"$host\"}[$interval])) by (mode) * 100 / count(node_cpu_seconds_total{$tag=\"$host\"}) by (mode) or sum(irate(node_cpu_seconds_total{$tag=\"$host\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{$tag=\"$host\"}) by (mode)",
     "legendFormat": "{{mode}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Plot Disk Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"nvme2n1\"}[5m])",
     "legendFormat": "Samsung"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_disk_written_bytes_total{device=\"nvme0c0n1\"}[5m])",
     "legendFormat": "WD",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"nvme1n1\"}[5m])",
     "legendFormat": "Kioxia"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{alias=\"$host\"} - (node_memory_MemAvailable_bytes{$tag=\"$host\"} or (node_memory_MemFree_bytes{$tag=\"$host\"} + node_memory_Buffers_bytes{$tag=\"$host\"} + node_memory_Cached_bytes{$tag=\"$host\"}))",
     "legendFormat": "Used",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Plot Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(node_filesystem_size_bytes{mountpoint=~\"/mnt/plotter[0-9]+\"}-node_filesystem_avail_bytes{mountpoint=~\"/mnt/plotter[0-9]+\"})/1000",
     "legendFormat": "{{mountpoint}}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{$tag=\"$host\"}",
     "legendFormat": "Load 1m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load5{$tag=\"$host\"}",
     "legendFormat": "Load 5m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load5%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load15{$tag=\"$host\"}",
     "legendFormat": "Load 15m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load15%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{$tag=\"$host\", device=\"enp2s0\"}[$interval]) or irate(node_network_transmit_bytes_total{$tag=\"$host\", device=\"enp2s0\"}[5m])",
     "legendFormat": "Outbound: {{ device }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}